### ISSUE TITLE
r-pillar does not respect version of r-base

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-pillar-feedstock#4]
## Observed behavior

The cb3 build of r-pillar (r341_0) is installed no matter the version of r-base that is requested.

```
$ conda create --dry-run -n test r-base=3.3.2 r-pillar | grep r-pillar-
    r-pillar-1.2.2             |           r341_0          86 KB  conda-forge
```
```
$ conda create --dry-run -n test r-base=3.4.1 r-pillar | grep r-pillar-
    r-pillar-1.2.2             |           r341_0          86 KB  conda-forge
```

It has multiple 3.3.2 builds available:

```
$ conda search 'r-pillar[channel=conda-forge]'
Loading channels: done
# Name                  Version           Build  Channel             
r-pillar                  1.1.0        r3.3.2_0  conda-forge         
r-pillar                  1.1.0        r3.4.1_0  conda-forge         
r-pillar                  1.2.1        r3.3.2_0  conda-forge         
r-pillar                  1.2.1        r3.4.1_0  conda-forge         
r-pillar                  1.2.2          r341_0  conda-forge 
```

## Expected behavior

I expected the 3.3.2 build of r-pillar to be installed when specifying `r-base=3.3.2`. This works properly for other R packages that have cb3 builds available, e.g.:

[r-recipes](https://github.com/conda-forge/r-recipes-feedstock)

```
$ conda create --dry-run -n test r-base=3.3.2 r-recipes | grep r-recipes-
    r-recipes-0.1.2            |         r3.3.2_0        1005 KB  conda-forge
```
```
$ conda create --dry-run -n test r-base=3.4.1 r-recipes | grep r-recipes-
    r-recipes-0.1.3            |           r341_0         1.0 MB  conda-forge
```

```
$ conda search 'r-recipes[channel=conda-forge]'
Loading channels: done
# Name                  Version           Build  Channel             
r-recipes                 0.1.2        r3.3.2_0  conda-forge         
r-recipes                 0.1.2        r3.4.1_0  conda-forge         
r-recipes                 0.1.3          r341_0  conda-forge   
```

[r-xfun](https://github.com/conda-forge/r-xfun-feedstock)

```
$ conda create --dry-run -n test r-base=3.3.2 r-xfun | grep r-xfun-
    r-xfun-0.1                 |         r3.3.2_0          44 KB  conda-forge
```
```
$ conda create --dry-run -n test r-base=3.4.1 r-xfun | grep r-xfun-
    r-xfun-0.2                 |           r341_0          96 KB  conda-forge
```

```
$ conda search 'r-xfun[channel=conda-forge]'
Loading channels: done
# Name                  Version           Build  Channel             
r-xfun                      0.1        r3.3.2_0  conda-forge         
r-xfun                      0.1        r3.4.1_0  conda-forge         
r-xfun                      0.2          r341_0  conda-forge   
```
## Environments tested

I tested this in the following environments:

conda-forge linux-anvil - tag [413e6f9cf655](https://hub.docker.com/r/condaforge/linux-anvil/builds/bjwnetwvhvpwrnnn7vyz4ec/) ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/4.4.100-boot2docker centos/6.9 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False

```
</details>

<br/>
macOS 10.10.5 ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
       user config file : /Users/jdblischak/.condarc
 populated config files : /Users/jdblischak/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.3
         python version : 3.6.4.final.0
       base environment : /Users/jdblischak/miniconda3-conda-forge  (writable)
           channel URLs : https://conda.anaconda.org/jdblischak/osx-64
                          https://conda.anaconda.org/jdblischak/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
          package cache : /Users/jdblischak/miniconda3-conda-forge/pkgs
                          /Users/jdblischak/.conda/pkgs
       envs directories : /Users/jdblischak/miniconda3-conda-forge/envs
                          /Users/jdblischak/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.4 Darwin/14.5.0 OSX/10.10.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by jdblischak** [comment]
I also confirmed this on Windows:

Windows 10 ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : C:\Users\john\Miniconda3
            shell level : 1
       user config file : C:\Users\john\.condarc
 populated config files : C:\Users\john\.condarc
          conda version : 4.5.4
    conda-build version : 3.0.21+636.gd8727a6a
         python version : 3.6.3.final.0
       base environment : C:\Users\john\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\john\Miniconda3\pkgs
                          C:\Users\john\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\john\Miniconda3\envs
                          C:\Users\john\AppData\Local\conda\conda\envs
                          C:\Users\john\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


```
</details>

**Comment by jdblischak** [comment]
Any ideas? @bgruening @isuruf I know that this also affects other R packages, but I haven't done any systematic logging of which ones are problematic.

**Comment by isuruf** [comment]
conda-build was broken for a while w.r.t r-base and this package was probably built in that time. Solution would be to mark this as broken and rebuild

**Comment by jdblischak** [comment]
Thanks @isuruf! Any advice for systematically identifying these problematic R packages?

**Comment by isuruf** [comment]
```
conda info r-*[channel=conda-forge] > tmp.txt
grep -i -B 5 'r-base$' tmp.txt
```

**Comment by isuruf** [comment]
```
https://conda.anaconda.org/conda-forge/linux-64/r-assertive-0.3_5-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.base-0.0_7-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.datetimes-0.0_2-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.types-0.0_3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-castor-1.3.3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-commonmark-1.5-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-dbplyr-1.2.1-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-kedd-1.0.3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-lexicon-0.7.4-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-lexicon-1.0.0-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-phylogeneticem-1.1.0-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-pillar-1.2.2-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-plot3drgl-1.0.1-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-reticulate-1.7-r341_0.tar.bz2
```

**Comment by jdblischak** [comment]
Got it. So any package that has a dependency of `r-base` with no version specified needs to be marked as broken. I was able to obtain the same list as you by running the following:

```
$ grep -B 17 '^    r-base$' tmp.txt | grep url | sed s/'url         : '//g | sort
https://conda.anaconda.org/conda-forge/linux-64/r-assertive-0.3_5-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.base-0.0_7-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.datetimes-0.0_2-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-assertive.types-0.0_3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-castor-1.3.3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-commonmark-1.5-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-dbplyr-1.2.1-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-kedd-1.0.3-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-lexicon-0.7.4-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-lexicon-1.0.0-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-phylogeneticem-1.1.0-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-pillar-1.2.2-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-plot3drgl-1.0.1-r341_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/r-reticulate-1.7-r341_0.tar.bz2
```

**Comment by bgruening** [comment]
@isuruf who is able to do this from the team?

**Comment by isuruf** [comment]
Technically all core members should have admin access anaconda.org/conda-forge. I'll update the anaconda.org with the new core members tonight.

**Comment by jdblischak** [comment]
Could someone please mark these packages as broken and confirm here once that is done? Then I will take responsibility for sending PRs to re-build these packages.

**Comment by ocefpaf** [comment]
@jdblischak only the linux version? Or all of that version/build number?

**Comment by jdblischak** [comment]
> only the linux version? Or all of that version/build number?

@ocefpaf This bug affects all the versions (I tested r-pillar across all 3 operating systems to confirm). The reason only linux-64 versions are listed above is because we ran `conda info` on a linux-64 machine.

Thanks!

**Comment by ocefpaf** [comment]
OK. I'll remove the build number `0` for `r341` on all platforms as listed below:

- [X] r-assertive 0.3_5 r341_0
- [X] r-assertive.base 0.0_7 r341_0
- [X] r-assertive.datetimes 0.0_2 r341_0
- [X] r-assertive.types 0.0_3 r341_0
- [X] r-castor 1.3.3 r341_0
- [X] r-commonmark 1.5 r341_0
- [X] r-dbplyr 1.2.1 r341_0
- [X] r-kedd 1.0.3 r341_0
- [X] r-lexicon 0.7.4 r341_0
- [X] r-lexicon 1.0.0 r341_0
- [X] r-phylogeneticem 1.1.0 r341_0
- [X] r-pillar 1.2.2 r341_0
- [X] r-plot3drgl 1.0.1 r341_0
- [X] r-reticulate 1.7 r341_0

**Comment by ocefpaf** [comment]
@jdblischak can you please review if I got the right packages?

**Comment by jdblischak** [comment]
Thanks @ocefpaf! For the most part they look good. Here are the few things I noticed:

For r-assertive.base, I think you may have marked too many as broken. The builds `0.0_7-r341_0` are broken, but not the `0.0_7-r3.4.1_0` builds. Is it possible for you to restore the `r3.4.1_0` builds that were created with conda-build 2?

https://anaconda.org/conda-forge/r-assertive.base/files?version=0.0_7

For r-assertive.types, it's the same issue where the `r3.4.1_0` builds were mistakenly labeled. Also, all the labels for this one are "bro" instead of "broken".

https://anaconda.org/conda-forge/r-assertive.types/files?version=0.0_3

**Comment by ocefpaf** [comment]
I made the modifications. Can you check again @jdblischak?

**Comment by jdblischak** [comment]
Looks good! Thanks @ocefpaf!

I confirmed the modifications by running the following:

```
conda create -n test --dry-run r-base=3.3.2 r-assertive.types
conda create -n test --dry-run r-base=3.4.1 r-assertive.types
```

**Comment by jdblischak** [comment]
Getting started on rebuilding these broken packages:

- [x]  r-assertive 0.3_5 r341_0 https://github.com/conda-forge/r-assertive-feedstock/pull/4
- [x] r-assertive.base 0.0_7 r341_0 https://github.com/conda-forge/r-assertive.base-feedstock/pull/3
- [x] r-assertive.datetimes 0.0_2 r341_0 https://github.com/conda-forge/r-assertive.datetimes-feedstock/pull/4
- [x] r-assertive.types 0.0_3 r341_0 https://github.com/conda-forge/r-assertive.types-feedstock/pull/5
- [x] r-castor 1.3.3 r341_0 https://github.com/conda-forge/r-castor-feedstock/pull/1
- [x] r-commonmark 1.5 r341_0 https://github.com/conda-forge/r-commonmark-feedstock/pull/3
- [x] r-dbplyr 1.2.1 r341_0 https://github.com/conda-forge/r-dbplyr-feedstock/pull/3
- [x] r-kedd 1.0.3 r341_0 https://github.com/conda-forge/r-kedd-feedstock/pull/1
- [x] r-lexicon 0.7.4 r341_0 https://github.com/conda-forge/r-lexicon-feedstock/pull/3
- [x] r-lexicon 1.0.0 r341_0 https://github.com/conda-forge/r-lexicon-feedstock/pull/2
- [x] r-phylogeneticem 1.1.0 r341_0 https://github.com/conda-forge/r-phylogeneticem-feedstock/pull/1
- [x] r-pillar 1.2.2 r341_0 https://github.com/conda-forge/r-pillar-feedstock/pull/5
- [x] r-plot3drgl 1.0.1 r341_0 https://github.com/conda-forge/r-plot3drgl-feedstock/pull/1
- [x] r-reticulate 1.7 r341_0 https://github.com/conda-forge/r-reticulate-feedstock/pull/5

**Comment by jdblischak** [comment]
@ocefpaf Quick question. Should I bump the build number when replacing a broken package?

**Comment by isuruf** [comment]
You should. Otherwise the package might not be uploaded

**Comment by ocefpaf** [comment]
> You should. Otherwise the package might not be uploaded

Yep.

**Comment by jdblischak** [comment]
Thanks for the assistance @isuruf @ocefpaf @bgruening. These should all be fixed now.

```
conda info r-*[channel=conda-forge] > tmp.txt
grep -B 17 '^    r-base$' tmp.txt | grep url | sed s/'url         : '//g | sort
```

In addition to the CI builds passing, I also manually confirmed that each `r341` build could be installed with `r-base=3.4.1` but not `r-base=3.3.2`.

There were a few hiccups:

* Two duplicate tarballs for r-assertive.datetimes were uploaded to Anaconda Cloud (https://github.com/conda-forge/r-assertive.datetimes-feedstock/issues/5). This was fixed by @bgruening marking one of the tarballs as broken and restarting the CI

* The CircleCI build mysteriously was not triggered for r-plot3drgl. I fixed this by sending an empty commit to trigger the build (https://github.com/conda-forge/r-plot3drgl-feedstock/pull/2).

The only remaining issue is that the new r-pillar packages have strange build strings. All the other packages have `r341_1`, yet the r-pillar build string is `r341h6115d3f_1`. I don't understand how this could happen. I rerendered each feedstock using the latest version of conda smithy (3.1.6) in the latest version of the condaforge/linux-anvil Docker container.

https://anaconda.org/conda-forge/r-pillar/files

Is there way to fix this?

**Comment by jdblischak** [comment]
Following up on this. I looked at the CI build logs, but I don't see why the build string for r-pillar was designated `r341h6115d3f_1` when all the others were properly designated as `r341_1`:

* [Travis log](https://travis-ci.org/conda-forge/r-pillar-feedstock/builds/396044337#L310)
* [AppVeyor log](https://ci.appveyor.com/project/conda-forge/r-pillar-feedstock/build/1.0.10#L229)
* [CircleCI log](https://circleci.com/gh/conda-forge/r-pillar-feedstock/14?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

The string `h6115d3f` isn't one of the commits in the r-pillar feedstock or in the [r-base](https://github.com/conda-forge/r-base-feedstock/search?q=h6115d3f&unscoped_q=h6115d3f) feedstock, so I don't understand where it came from.

<br/>
Results from running `conda info r-pillar[build=r341h6115d3f_1]`:
<details>

```
$ conda info r-pillar[build=r341h6115d3f_1]
r-pillar 1.2.2 r341h6115d3f_1
-----------------------------
file name   : r-pillar-1.2.2-r341h6115d3f_1.tar.bz2
name        : r-pillar
version     : 1.2.2
build string: r341h6115d3f_1
build number: 1
channel     : https://conda.anaconda.org/conda-forge/linux-64
size        : 98 KB
arch        : x86_64
constrains  : ()
license     : GPL-3
license_family: GPL3
md5         : b537bb5a02d0419856643d4dd129eb15
platform    : linux
subdir      : linux-64
timestamp   : 1529838427704
url         : https://conda.anaconda.org/conda-forge/linux-64/r-pillar-1.2.2-r341h6115d3f_1.tar.bz2
dependencies:
    r-base >=3.4.1,<3.4.2.0a0
    r-cli >=1.0.0
    r-crayon >=1.3.4
    r-rlang >=0.2.0
    r-utf8 >=1.1.3
```
</details>

**Comment by isuruf** [comment]
That's expected because you have a host section here. https://conda.io/docs/user-guide/tasks/build-packages/variants.html?highlight=hash#differentiating-packages-built-with-different-variants

**Comment by jdblischak** [comment]
> That's expected because you have a host section here.

Thanks for the explanation, @isuruf. Now I understand why this package behaved differently than all the others I fixed. I ran the conda skeleton helper in PR #5 to format this recipe, which added all the new cb3 fields.
